package client;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CheckTrainWSDelegate", targetNamespace = "http://service/")
public interface CheckTrainWSDelegate {

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns javax.xml.ws.Response<client.CheckTrainResponse>
	 */
	@WebMethod(operationName = "checkTrain")
	@RequestWrapper(localName = "checkTrain", targetNamespace = "http://service/", className = "client.CheckTrain")
	@ResponseWrapper(localName = "checkTrainResponse", targetNamespace = "http://service/", className = "client.CheckTrainResponse")
	public Response<CheckTrainResponse> checkTrainAsync(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @param asyncHandler
	 * @return returns java.util.concurrent.Future<? extends java.lang.Object>
	 */
	@WebMethod(operationName = "checkTrain")
	@RequestWrapper(localName = "checkTrain", targetNamespace = "http://service/", className = "client.CheckTrain")
	@ResponseWrapper(localName = "checkTrainResponse", targetNamespace = "http://service/", className = "client.CheckTrainResponse")
	public Future<?> checkTrainAsync(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2,
			@WebParam(name = "asyncHandler", targetNamespace = "") AsyncHandler<CheckTrainResponse> asyncHandler);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<client.Train>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkTrain", targetNamespace = "http://service/", className = "client.CheckTrain")
	@ResponseWrapper(localName = "checkTrainResponse", targetNamespace = "http://service/", className = "client.CheckTrainResponse")
	public List<Train> checkTrain(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

}
