package client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CheckTrainWSService service = new CheckTrainWSService();
 * CheckTrainWSDelegate portType = service.getCheckTrainWSPort();
 * portType.checkTrainAsync(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CheckTrainWSService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/CheckTrain/CheckTrainWSPort?wsdl")
public class CheckTrainWSService extends Service {

	private final static URL CHECKTRAINWSSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(client.CheckTrainWSService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = client.CheckTrainWSService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/CheckTrain/CheckTrainWSPort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/CheckTrain/CheckTrainWSPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CHECKTRAINWSSERVICE_WSDL_LOCATION = url;
	}

	public CheckTrainWSService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CheckTrainWSService() {
		super(CHECKTRAINWSSERVICE_WSDL_LOCATION, new QName("http://service/",
				"CheckTrainWSService"));
	}

	/**
	 * 
	 * @return returns CheckTrainWSDelegate
	 */
	@WebEndpoint(name = "CheckTrainWSPort")
	public CheckTrainWSDelegate getCheckTrainWSPort() {
		return super.getPort(new QName("http://service/", "CheckTrainWSPort"),
				CheckTrainWSDelegate.class);
	}

}
