package common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MyServiceDelegate", targetNamespace = "http://common/")
public interface MyServiceDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SayHi")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "SayHi", targetNamespace = "http://common/", className = "common.SayHi")
	@ResponseWrapper(localName = "SayHiResponse", targetNamespace = "http://common/", className = "common.SayHiResponse")
	public String sayHi(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
