package test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * JavaComplexTypeService service = new JavaComplexTypeService();
 * JavaComplexTypeDelegate portType = service.getJavaComplexTypePort();
 * portType.getPersonAsync(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "JavaComplexTypeService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/ComplexClass/JavaComplexTypePort?wsdl")
public class JavaComplexTypeService extends Service {

	private final static URL JAVACOMPLEXTYPESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(test.JavaComplexTypeService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = test.JavaComplexTypeService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:8080/ComplexClass/JavaComplexTypePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ComplexClass/JavaComplexTypePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		JAVACOMPLEXTYPESERVICE_WSDL_LOCATION = url;
	}

	public JavaComplexTypeService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public JavaComplexTypeService() {
		super(JAVACOMPLEXTYPESERVICE_WSDL_LOCATION, new QName(
				"http://service/", "JavaComplexTypeService"));
	}

	/**
	 * 
	 * @return returns JavaComplexTypeDelegate
	 */
	@WebEndpoint(name = "JavaComplexTypePort")
	public JavaComplexTypeDelegate getJavaComplexTypePort() {
		return super.getPort(
				new QName("http://service/", "JavaComplexTypePort"),
				JavaComplexTypeDelegate.class);
	}

}
